[project]
name = "panda-distributed-pick-place"
version = "0.1.0"
description = "Prototyping/notebook environment for the distributed ROS 2 Panda pick-and-place demo"
authors = [
    {name = "Sebastian Schroeter",email = "sebastian.schroeter@mailbox.org"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=1.26.0,<3.0.0)",
    "scipy (>=1.11.0,<2.0.0)",
    "matplotlib (>=3.8.0,<4.0.0)",
    "notebook (>=7.0.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
