<?xml version="1.0"?>
<package format="3">
  <name>panda_demo_description</name>
  <version>0.1.0</version>
  <description>Panda description extended for Gazebo Harmonic and gz_ros2_control.</description>
  <maintainer email="sebastian.schroeter@mailbox.org">Sebastian Schroeter</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>moveit_resources_panda_description</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

