<?xml version="1.0"?>
<package format="3">
  <name>panda_grasp_adapter</name>
  <version>0.1.0</version>
  <description>ROS services backed by Gazebo Transport for DetachableJoint.</description>
  <maintainer email="sebastian.schroeter@mailbox.org">Sebastian Schroeter</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>gz_msgs_vendor</depend>
  <depend>gz_transport_vendor</depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
